You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Return the max sliding window.

Input: nums = [1,3,-1,-3,5,3,6,7], k = 3 

Output: [3,3,5,5,6,7]

Explanation: 

Window position                Max

---------------               -----

[1  3  -1] -3  5  3  6  7       3

 1 [3  -1  -3] 5  3  6  7       3

 1  3 [-1  -3  5] 3  6  7       5

 1  3  -1 [-3  5  3] 6  7       5

 1  3  -1  -3 [5  3  6] 7       6

 1  3  -1  -3  5 [3  6  7]      7

In [8]:
import numpy as np
import collections
import timeit

In [9]:
input_nums = np.random.randint(10,size=(1000))
print(input_nums)

[2 8 9 4 9 6 4 9 4 4 2 7 5 4 0 0 9 5 9 0 9 6 7 7 0 4 0 1 1 5 1 8 4 0 2 7 5
 0 4 9 4 8 8 8 7 4 8 0 4 9 8 4 4 0 7 0 8 3 7 4 0 1 6 8 1 4 9 2 5 8 2 6 4 0
 3 8 2 8 3 3 1 5 2 6 4 7 1 3 3 5 5 6 8 9 8 2 6 6 8 6 9 2 5 9 7 6 3 9 9 7 9
 6 9 4 8 3 6 8 4 6 1 2 5 5 3 0 7 4 1 6 5 0 8 5 7 6 1 3 8 2 0 3 3 0 3 1 5 3
 7 8 2 3 4 2 0 2 0 9 5 3 6 1 1 6 2 7 5 1 9 2 6 1 2 5 4 5 4 8 8 4 3 4 8 7 2
 5 0 5 8 4 8 1 0 3 1 7 3 3 6 5 8 3 1 2 4 2 4 7 9 4 6 6 3 2 7 8 8 1 9 8 4 3
 0 1 4 3 0 3 4 3 8 5 5 9 2 6 5 4 8 8 8 0 5 6 9 5 9 9 1 0 9 6 1 4 2 0 3 8 0
 5 7 5 3 4 6 2 4 3 2 8 6 0 5 0 0 0 5 2 5 1 1 0 6 5 0 0 1 9 6 9 2 2 3 4 0 2
 8 0 7 2 6 8 1 7 5 4 8 6 9 3 8 4 0 8 4 5 9 6 3 1 0 4 3 7 2 5 1 8 3 0 8 6 1
 8 2 4 6 7 9 7 1 7 4 5 3 2 7 4 9 2 9 2 3 2 6 1 4 2 8 6 4 1 3 5 1 5 2 3 0 9
 3 6 1 3 4 4 7 8 5 6 4 3 3 1 7 0 3 5 5 7 7 0 1 8 2 4 7 7 9 0 2 3 3 6 1 2 7
 5 0 2 9 3 7 3 1 7 3 5 1 8 8 1 2 4 7 2 1 8 7 6 8 0 6 1 7 2 0 1 3 2 7 5 7 6
 0 9 2 1 5 9 2 0 1 0 5 7 0 3 7 8 1 4 1 3 5 2 9 2 3 7 7 5 3 6 3 1 2 9 7 0 8
 8 6 0 7 0 3 8 0 1 3 9 9 

First approach uses numpy and matrices to display a nice matrix visualisation of each window slice.

Not very fast as has to go over many zeros in the final matrix when finding max.

In [10]:
def matrix_max_finder(initial_array, mask_no):
    con_length = np.zeros((len(initial_array), len(initial_array)), dtype=int)
    for _n in range(mask_no):
        con_length += np.eye(len(initial_array),k= _n , dtype=int)#- N//2 ) 
    # print(con_length)
    con_length = (con_length[:len(initial_array)-mask_no+1,:])
    masked_array = np.multiply(initial_array,con_length)
    # print(masked_array)
    max_list = np.max(masked_array, axis=1)
    return max_list

Building a function to using a single stack to improve time efficiency.

Not as visual as previous method, but significantly faster. 

In [11]:

def one_list_linear(initial_array, mask_length):
        index_stack = collections.deque()
        out = []
        for index, num in enumerate(initial_array):
            while index_stack and initial_array[index_stack[-1]] < num:
                index_stack.pop()
            index_stack.append(index)
            # print("\t Added i to d")
            if index_stack[0] == index - mask_length:
                index_stack.popleft()
            if index>=mask_length-1:
                out.append(initial_array[index_stack[0]])
        return out

In [12]:
def matrix_max_finder_sliding_window(initial_array: np.ndarray, mask_no: int) -> np.ndarray:
    """
    Finds the maximum value of each consecutive sequence of length `mask_no`
    in the `initial_array` and returns a list of these maximum values.

    Args:
        initial_array: A numpy array of integers.
        mask_no: An integer representing the length of the consecutive sequence.

    Returns:
        A numpy array of integers representing the maximum values of each consecutive
        sequence of length `mask_no`.
    """
    # Create a sliding window of size `mask_no`
    window = np.lib.stride_tricks.sliding_window_view(initial_array, mask_no)

    # Find the maximum value of each window
    max_list = np.max(window, axis=1)

    return max_list


In [15]:
time(matrix_max_finder(input_nums,20))


CPU times: user 20.5 ms, sys: 13.6 ms, total: 34.1 ms
Wall time: 32.3 ms


array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,

In [16]:
time(one_list_linear(input_nums,20))

CPU times: user 457 µs, sys: 100 µs, total: 557 µs
Wall time: 766 µs


[9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,


In [17]:
time(matrix_max_finder_sliding_window(input_nums,20))

CPU times: user 228 µs, sys: 704 µs, total: 932 µs
Wall time: 1.41 ms


array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,